data:
  raw_data_path: "/src/data/raw/processed_data.csv"  # Path to your transactions file
  app_mappings_path: "/src/data/raw/app_mappings_2st_round.csv"  # Path to app mappings
  exploded_df_path: "/out/exploded_df.pkl"  # Cache for exploded dataframe
  sequences_path: "/out/sequences.pkl"  # Cache for sequences
  vocab_path: "/out/app_to_idx.pkl"  # Cache for vocabulary
  app_quality_path: "config/app_productivity_scores.yaml"

extra_inputs:
  time: false
  app_quality: false
  mouseClicks: false
  mouseScroll: false
  keystrokes: false
  mic: false
  camera: false

model:
  vocab_size: null  # Will be set automatically based on vocabulary
  seq_length: 16
  batch_size: 512
  learning_rate: 1e-4
  d_model: 64
  nhead: 4
  num_encoder_layers: 3
  dim_feedforward: 256
  dropout: 0.1

training:
  num_epochs: 200
  mask_prob: 0.15
  test_size: 0.2
  random_seed: 42
  lr: 1e-4
  device: "cuda"  # Will fall back to CPU if CUDA not available
  pretrained_model_path: null
  save_model_path: "/out/app_sequence_model_apps.pt"
  preload_dataset: true
