data:
  raw_data_path: "data/raw/day_point_dataset_v5.csv"
  app_mappings_path: "data/raw/app_mappings_2st_round.csv" 
  exploded_df_path: "data/processed/exploded_df.pkl"
  sequences_path: "data/processed/sequences.pkl"
  vocab_path: "data/processed/app_to_idx.pkl"

model:
  vocab_size: null
  seq_length: 64
  batch_size: 512
  learning_rate: 1e-4
  d_model: 64
  nhead: 4
  num_encoder_layers: 3
  dim_feedforward: 128
  dropout: 0.1

training:
  num_epochs: 200
  mask_prob: 0.15
  test_size: 0.2
  random_seed: 42
  lr: 1e-4
  device: "cuda"
  pretrained_model_path: "models/app_sequence_model_3st_round.pt"
  save_model_path: "models/app_sequence_model_4st_round.pt"
  preload_dataset: true
