10.0.11.166:9125: 5
10.1.52.141:8124: 6
10.2.2.18: 6
365online.com: 6
4dayjobs.de: 5
6807217.app.netsuite.com: 6
8x8_Work: 7
AI_Assistance: 7
AI_Assistance-Local: 7
Accessibility-Local: 7
Administration-Local: 7
Adobe_Acrobat: 8
Adobe_Acrobat_2020: 8
Adobe_Acrobat_DC: 8
Adobe_Acrobat_Reader: 8
Adobe_Illustrator_2023: 9
Adobe_Illustrator_2024: 8
Adobe_InDesign_2024: 9
Adobe_Photoshop_2021: 8
Adobe_Photoshop_2024: 8
Adult_&_Dating: 2
Agriculture_&_Environment: 7
Aircall: 7
Analytics: 8
Analytics-Local: 9
Android_Studio: 10
AnyDesk: 8
Application_Frame_Host: 4
AutoCAD: 9
Automotive_&_Services: 6
Automotive_&_Services-Local: 6
Banking: 7
Bitrix24: 7
Bitvise_SSH_Client: 9
Blogging: 5
Bluebeam_Revu: 8
Business: 8
Business_Software: 8
Business_Software-Local: 7
CRM: 8
CRM-Local: 9
Calendar_&_Scheduling: 8
Calendar_&_Scheduling-Local: 8
Change_Healthcare_Radiology_Solutions_Radiology_Station: 6
Cisco_Jabber_Application: 6
Citrix_Workspace: 8
Cloud_Services: 10
Cloud_Services-Local: 9
Code: 10
Communication: 7
Communication-Local: 7
Concentration_Lost: 1
"Conexi\xF3n_a_Escritorio_remoto": 8
Construction: 7
Construction-Local: 7
Consulting: 7
Creative_&_Design: 8
Creative_&_Design-Local: 8
Cursor: 6
Customer_Support: 7
Customer_Support-Local: 8
Cybersecurity: 8
Cybersecurity-Local: 8
Database_Management-Local: 9
Development: 10
Development-Local: 10
Dexterity_for_Microsoft_Dynamics_GP: 8
Discord: 3
Documentation: 9
Documentation-Local: 9
Documents_&_Collaboration: 9
Documents_&_Collaboration-Local: 9
Documents_&_Storage: 9
Documents_&_Storage-Local: 8
DraftworX: 9
E-commerce: 5
E-commerce-Local: 6
Education_&_Learning: 9
Engineering: 9
Events: 6
EveryWeigh: 5
Explorador_de_Windows: 8
Family_&_Parenting: 4
Figma: 9
FileZilla: 7
File_Sharing-Local: 8
Finance: 7
Finance-Local: 7
Finder: 8
Food: 5
GB_Logs: 6
Gaming: 2
Gaming-Local: 2
GoTo: 7
Greenshot: 7
Health_&_Wellness: 5
Health_&_Wellness-Local: 5
Herramienta_Recortes: 6
Home_Stuff: 5
Hospitality: 5
Hosting_&_Domains: 6
Hosting_&_Domains-Local: 7
Human_Resources: 7
Human_Resources-Local: 8
Hyperdrive: 6
IT_Services: 8
IT_Services-Local: 8
Industry_&_Manufacturing: 7
Infloww: 5
Insurance: 5
Insurance-Local: 7
Internet_Service_Provider: 6
IoT: 8
Job_Board: 6
Job_Board-Local: 6
Kareo: 6
Kumospace: 5
Language_&_Translation: 7
Language_&_Translation-Local: 8
Legal_&_Compliance: 7
Legal_&_Compliance-Local: 8
Local_Development: 10
Local_Development-Local: 10
Localization_&_Translation-Local: 8
Logistics_&_Transportation: 6
Logistics_&_Transportation-Local: 7
Mail-Local: 7
Marketing_&_Advertising: 6
Marketing_&_Advertising-Local: 6
Media: 5
Media-Local: 4
MicroStaffer: 6
Microsoft_Calculator: 6
Microsoft_Excel: 10
Microsoft_Management_Console: 9
Microsoft_OneNote: 8
Microsoft_Outlook: 8
Microsoft_PowerPoint: 9
Microsoft_SQL_Server: 9
Microsoft_StickyNotes: 5
Microsoft_Teams: 8
Microsoft_Word: 10
Miscellaneous: 4
Miscellaneous-Local: 4
Music_&_Audio_Entertainment: 2
Music_&_Audio_Entertainment-Local: 2
Networking-Local: 7
News-Local: 2
Nonprofit_&_Community: 6
Notepad: 6
Notepad++: 8
Notes-Local: 5
Operating_System-Local: 8
Other_Entertainment: 3
Other_Entertainment-Local: 3
Outlook: 8
Pages: 6
Paint: 5
PaperBOS: 6
Pause: 1
Postman: 9
Printing_&_Publishing: 6
Printing_&_Publishing-Local: 6
Private_Links: 3
Project_Management: 8
Project_Management-Local: 8
Property_&_Real_Estate: 6
PuTTY_suite: 9
Public_Sector_&_Politics: 3
Public_Sector_&_Politics-Local: 6
QuoteWerks: 7
Recruitment: 7
Remote_Access-Local: 8
Remote_Desktop_Connection: 8
Remote_Support-Local: 8
RingCentral: 7
SAF: 5
Sales: 8
Sales-Local: 8
Science_&_Research: 8
Search_Engine: 6
Search_Engine-Local: 6
Search_application: 6
Service_&_Support: 7
Skype: 7
Slack: 8
Snagit: 7
Snipping_Tool: 6
Social_Networking: 2
Social_Networking-Local: 3
Sports_&_Recreation: 4
Surveys_&_Research: 6
TASRuntime: 5
Telecommunications: 7
Telecommunications-Local: 7
Testing: 7
Testing-Local: 9
Thunderbird: 7
Time_Tracking: 8
Time_Tracking-Local: 8
Travel_&_Tourism: 5
Travel_&_Tourism-Local: 6
Tray: 5
Turbo_Virtual_Machine: 8
"UPS_WorldShip\xAE_Shipping_System": 7
Utilities_&_Tools: 6
Utilities_&_Tools-Local: 6
VMware_Horizon_Client: 8
VMware_Workstation: 8
"VNC\xAE": 7
Video_Conferencing: 7
Video_Conferencing-Local: 7
Video_Entertainment: 2
Video_Entertainment-Local: 2
Visual_Studio_Code: 10
Vonage_Business: 7
Vysor: 6
Weather-Local: 4
Webex_for_Windows_Host: 7
Website_Management: 7
WhatsApp: 3
Windows_Explorer: 8
Windows_Shell_Experience_Host: 6
Windows_Wordpad_Application: 5
Workpuls: 9
Xactimate_online_Estimate_Writer: 8
Zoom: 8
aaa-nynf.modria.com: 5
about:blank: 1
acc.autodesk.com: 8
access.brivo.com: 6
accounts.google.com: 6
acuity.com: 7
adclickafrica-squad.monday.com: 7
adclickafrica2020-my.sharepoint.com: 8
admin.box.co.uk: 6
admin.dev.1939api.com: 7
admin.exchange.microsoft.com: 8
admin.microsoft.com: 8
admin.shopify.com: 7
adult.contents.fc2.com: 1
airbnb.com: 5
amazon.com: 3
analytics.google.com: 9
andrew---draftworx.monday.com: 7
aoins.com: 4
apdprinting.com: 5
api.whatsapp.com: 3
app.alegra.com: 7
app.asana.com: 8
app.callrail.com: 7
app.clickup.com: 8
app.clientmagnet.ai: 6
app.clio.com: 6
app.companycam.com: 7
app.confidolegal.com: 6
app.detrack.com: 6
app.drata.com: 6
app.grammarly.com: 8
app.hubspot.com: 8
app.insightful.io: 7
app.justcall.io: 7
app.olitt.com: 6
app.ordoro.com: 7
app.pandadoc.com: 8
app.pipelinecrm.com: 7
app.ramp.com: 7
app.slack.com: 8
app.smartsheet.com: 8
app.soakandsleep.test: 5
app.vanta.com: 7
app.webpt.com: 6
app02.us.bill.com: 8
apps.24hrcash.ca: 5
apps.availity.com: 7
apps.rackspace.com: 7
appsuite.cloudoon.com: 6
ascendtms.com: 6
assc.hh2.com: 6
atc.itglue.com: 7
au.unleashedsoftware.com: 6
aw-conglomerate.monday.com: 8
b2b.statefarm.com: 7
backend.laptopoutlet.co.uk: 5
bamboo.flagstar.com:8443: 7
beachhavenjewelrystore.zendesk.com: 7
bing.com: 6
bitbucket.flagstar.com:8443: 9
bizagigo.bancolombia.corp: 6
books.viventa.co: 6
box.co.uk: 7
bp-localjob.whitelabelportal.de: 6
bp-stanz.whitelabelportal.de: 5
bp-yourfirm2.whitelabelportal.de: 6
bridgebm.rsweb247.com: 6
buggy.3cx.us: 4
buggy.voyagergm.io: 4
business.facebook.com: 3
businessonline-boi.com: 6
c: 1
c001.eagleeyenetworks.com: 6
calculator.net: 5
calendar.google.com: 9
campus-supportzebra.talentlms.com: 7
canva.com: 8
care2.onetouchhealth.net: 5
central.uber.com: 6
cg.mycitygoddess.com: 2
chatgpt.com: 7
chrome://newtab/: 1
chromewebdata: 3
claims.zirmed.com: 7
claimsco.onelogin.com: 7
claude.ai: 7
cli.transportpro.net: 5
client.lawspades.com: 7
clientsfuel.softphone.pro: 6
clipboard.health: 6
clipboardhealth.atlassian.net: 7
clipboardhealth.lessonly.com: 7
clipboardhealth.zendesk.com: 7
cloud.draftworx.com: 8
cms.littlescientist.cn: 6
colab.research.google.com: 9
confidolegal.atlassian.net: 7
console.cloud.google: 10
console.cloud.google.com: 10
console.druva.com: 7
console.firebase.google.com: 10
crm.zoho.com: 7
cron1001.contents.i.fc2.com: 4
cron1001.market.i.laxd.com: 5
dash.cloudoon.com: 5
dashboard-r4.tagalys.com: 5
dashboard.aircall.io: 8
dashboard.checkr.com: 7
dashboard.stripe.com: 9
dbia.com: 6
deepl.com: 7
dell.com: 6
demo.renesan.com: 6
depop.com: 2
desktop.shannonhealth.local: 8
dev.adclickafrica.com: 6
dev.azure.com: 10
devlogistics.krispykreme.co.uk: 6
dice.com: 6
diffchecker.com: 7
discord.com: 3
doc.web100.com.ua: 6
docs.google.com: 9
draftworx-my.sharepoint.com: 8
drive.google.com: 9
drive.usercontent.google.com: 8
dropbox.com: 9
dsr.prestodemos.com: 5
eams.dwc.ca.gov: 6
eamsdm.dwc.ca.gov: 6
ec-service.asus.com: 5
eclipse.exe: 8
efaidnbmnnnibpcajpcglclefindmkaj: 3
efaxcorporate.com: 6
elevenlabs.io: 8
eligibility.zirmed.com: 7
elitebm.rsweb247.com: 6
email.rackspace.com: 5
emea.store.asus.com: 5
emeastage.store.asus.com: 5
emergefreightalliance.com: 6
employees-jboss8.platform.web100.com.ua: 5
employers.indeed.com: 7
epicuat.lacitizens.com: 6
etsy.com: 3
eu2-cloud.acronis.com: 9
evernote.com: 8
exxonmobilbusinessonline.com: 6
facebook.com: 2
fasttrackleasingllc.crm.dynamics.com: 8
fbctrust-my.sharepoint.com: 7
fedex.com: 7
figma.com: 9
fivetechcouk-my.sharepoint.com: 7
flagstar-my.sharepoint.com: 8
flagstar.service-now.com: 8
flagstar.sharepoint.com: 8
fleetcontrol.invers.com: 6
freepik.com: 6
ft.ebrook.com.tw: 5
g030101p01x.ukg.net: 7
galaxy.epic.com: 6
gateway.appone.net: 4
getwitz-my.sharepoint.com: 8
github.com: 10
gitlab.fc2.com: 9
global.americanexpress.com: 7
go.xero.com: 7
goddiva.co.uk: 3
goddiva.us: 2
google.co.uk: 6
google.com: 6
grantthorntonco-my.sharepoint.com: 8
gravitypayments.lightning.force.com: 7
gtmdjd.com: 3
hashnode.com: 7
hdap.nycb.com: 7
helloteam.atlassian.net: 7
helpdesk-ec.shannonhealth.org: 8
helpdesk.shannonhealth.org: 7
highway.com: 5
huggingface.co: 9
iapps.courts.state.ny.us: 7
ibm.com: 8
idp.agillink.com: 7
ilovepdf.com: 6
immix.prosegurmonitoring.com: 6
instagram.com: 2
intune.microsoft.com: 9
iowaonline.state.ia.us: 6
itreasury.regions.com: 7
jdpowerconnect.com: 6
jira.247commerce.co.uk: 8
jira.flagstar.com:8443: 8
jira.web100.com.ua: 8
jira.yggdrasilgaming.com: 8
justcall.io: 7
kalaydo.de: 5
kards.com: 3
kards.exe: 3
kashlegal.filevineapp.com: 6
kuiper.shannonhealth.local: 5
kumospace.com: 5
latamforwardersclub.com: 5
launcher.yggdrasilgaming.com: 5
lauprint.com: 5
learn.microsoft.com: 10
lfeldkdefleohakfkjghkccabpikpeeo: 3
license.draftworx.com: 7
lightning.ai: 9
link.24hrcash.ca: 5
linkedin.com: 5
lmu-app.dev.flagstar.com: 6
localhost: 10
localhost:3000: 10
localhost:49431: 10
localhost:8000: 10
localhost:8069: 9
localjob.de: 5
login.agillink.com: 6
login.microsoftonline.com: 5
lookerstudio.google.com: 9
loom.com: 7
mail.google.com: 7
mail.yahoo.com: 3
mail.yandex.com: 6
mcstaging.krispykreme.co.uk: 6
mcstaging.xupes.com: 6
mcstaging2.krispykreme.co.uk: 6
meet.google.com: 8
metabase.cbh.rocks: 7
mirasafety.com: 6
mp.mygoddiva.com: 2
mp.tradegala.net: 6
msn.com: 2
muisca.dian.gov.co: 6
my.openphone.com: 7
myapps.paychex.com: 6
mycitygoddess.com: 2
myfleetcenter.com: 6
mygoddiva.co.uk: 2
na.myconnectwise.net: 7
newpace.pacesetterclaims.net: 5
nexus.uat.privilegemovies.com: 5
nmtech.atlassian.net: 8
northstarforwarders.com: 5
nova.epic.com: 6
nova.flagstar.com: 7
novitasphere.com: 7
nsyncbilling.renesan.com: 5
octane-clean.azurewebsites.net: 7
octane-dev12.azurewebsites.net: 6
octane-dev13.azurewebsites.net: 6
office.com: 9
oh03.partnerxe.com: 5
one.dat.com: 6
onlinebanking.usbank.com: 7
open.spotify.com: 3
oppo-upgrade.retaildirectgroup.com: 5
outlook.office.com: 8
outlook.office365.com: 8
palmcareers.lightning.force.com: 5
palmcareers.myavionte.com: 5
palmhealthresources.sharefile.com: 8
pandora.com: 2
partner-academy.databricks.com: 9
partners.fresha.com: 6
partners.geico.com: 5
paypal.com: 6
pdamericabm.renesan.com: 5
pearprovider.com: 6
people.zoho.com: 6
phoenix.transactiongateway.com: 6
photos.exe: 3
photosapp.exe: 3
phpstorm64.exe: 9
piedpiper.edgetier.com: 6
pipeline-live-userdata.s3.amazonaws.com: 7
portal-clean1.whitelabelportal.de: 6
portal-clean2.whitelabelportal.de: 6
portal-dev1.whitelabelportal.de: 6
portal-dev12.whitelabelportal.de: 6
portal-dev13.whitelabelportal.de: 6
portal-dev6.whitelabelportal.de: 6
portal-lasc.journaltech.com: 6
portal.azure.com: 10
portal.renesan.com: 6
portal.vantagerecreationalfinance.com: 5
portal.web100.com.ua: 4
prestodemos.com: 5
prestofolders.com: 5
prod-afsvision.fbc.afscommerce.net: 6
projects.zoho.com: 7
prosegur365.sharepoint.com: 8
provider.alturamso.com: 6
pv2300r7adhc001.flagstar.com:3780: 7
pwastagingfe.ingredientsonline.com: 5
qa-testlab.litmoseu.com: 7
qatestlab-my.sharepoint.com: 7
qatestlab.testrail.com: 7
qbo.intuit.com: 7
quora.com: 3
rebuildrelief.pipedrive.com: 7
reddit.com: 2
rencore.visualstudio.com: 9
resortag-my.sharepoint.com: 8
retaildirect.atlassian.net: 7
rhymetec.freshdesk.com: 8
ridewithvia.tfaforms.net: 6
ros.ie: 6
rsbilling.rsweb247.com: 6
rwsolutions-freight.activehosted.com: 6
s3.us-west-2.amazonaws.com: 7
searchhost.exe: 4
secure.chase.com: 7
secure.fmins.com: 6
semrush.com: 9
shannonhealth-sso.prd.mykronos.com: 7
sherlock.epic.com: 6
ship12.shipstation.com: 6
shopify-staging.bigdxpro.com: 6
sicherdirdenjob.de: 5
sit-afsvision.fbc.afscommerce.net: 6
sites.google.com: 8
sloan.24hrcash.ca: 4
smesouthafrica.co.za: 5
solvealltest.develop.helloteam.us: 6
source6.flagstar.com:8443: 7
sretaildxb-my.sharepoint.com: 8
sretaildxb.sharepoint.com: 8
stackoverflow.com: 10
stag10.asusstore.co.uk: 5
staging.olitt.com: 5
staging.soakandsleep.com: 5
stagingpro-staging.bigdxpro.com: 6
statics.teams.cdn.office.net: 6
staticstaging.yggdrasilgaming.com: 5
staticstagingcw.yggdrasilgaming.com: 5
stellenanzeigen.de: 5
store-v6q95r5n91.mybigcommerce.com: 5
sub.boldapps.net: 6
support.clipboardhealth.com: 7
tap.allmerica.com: 6
tc.renesan.com: 5
teams.microsoft.com: 8
temp-mail.org: 3
tenhil.atlassian.net: 8
tfl-staging.247commerce.co.uk: 6
tools.usps.com: 6
toscacommander.exe: 6
tpo.flagstar.com: 7
tradeonlyfolders.com: 5
training.knowbe4.com: 8
translate.google.com: 7
translate.google.com.ua: 7
trends.google.com: 7
truehost.co.ke: 5
truehost.elastix.com: 5
tyler-aaany.okta.com: 7
uapi.union-andina.net: 6
udemy.com: 8
udemytestsuite.testrail.io: 6
ups.com: 6
us-east-1.console.aws.amazon.com: 9
us02web.zoom.us: 8
usa.ingrammicro.com: 6
user-guides.web100.com.ua: 6
user-supportweb100.helprace.com: 6
usnetads.com: 2
vbilling.rsweb247.com: 6
veeamscp.acorntechservices.com:1280: 6
visonex.sharepoint.com: 8
vortexiq.ai: 7
voyager-global-mobility.frontapp.com: 6
voyagm.monday.com: 7
vrbo.com: 5
vrf365.sharepoint.com: 8
vscp-prd1: 5
vsvcenter2.shannonhealth.local: 8
web.jibble.io: 7
web.skype.com: 7
web.whatsapp.com: 3
wetransfer.com: 7
whatsapp.exe: 3
wholesalepocketfolders.ca: 5
wmonin.flagstar.com: 5
workdrive.zoho.com: 8
workforcenow.adp.com: 8
ww5.autotask.net: 6
www-sf.talispoint.com: 6
x3.sharafretail.com: 5
xactanalysis.com: 6
xactimate.com: 8
xupes.com: 5
yahoo.com: 3
yourfirm.de: 5
youtube.com: 2
zdravko.hellopaychex.helloteam.us: 4
zillow.com: 5
zinfandel.centrastage.net: 6
zinfandel.rmm.datto.com: 7
"\u041F\u0440\u043E\u0432\u043E\u0434\u043D\u0438\u043A": 8
"\u041F\u0440\u043E\u0432\u0456\u0434\u043D\u0438\u043A_Windows": 8
"\u200EWhatsApp": 3
